"""DAYTRADE-003: Deterministic research-only Opening Range Breakout (ORB) package."""
from __future__ import annotations

from .dataset_contract import (
    TwoStageDatasetManifest,
    compute_manifest_sha256,
    manifest_from_dict,
    manifest_from_json,
    manifest_to_dict,
    manifest_to_json,
    validate_dataset_manifest_invariants,
)
from .evaluator import ORBEvaluator, verify_holdout_access_guard
from .execution import (
    build_trade_record,
    check_protective_stop_hit,
    check_same_bar_stop_collision,
    check_stop_entry_trigger,
)
from .indicators import compute_adv14, compute_atr14_wilder, compute_relative_volume
from .metrics import (
    compute_study_metrics,
    evaluate_validation_disposition,
    run_session_date_bootstrap,
)
from .models import (
    BootstrapCI,
    Candidate,
    DailyBar,
    DataIntegrityError,
    Direction,
    ExitReason,
    GateEvaluationResult,
    HoldoutAccessDeniedError,
    HoldoutAccessProof,
    MinuteBar,
    OpeningRange,
    OpeningRangeVolumeObservation,
    OrderIntent,
    OrderStatus,
    RankedCandidate,
    SessionResult,
    StudyMetrics,
    StudyResult,
    Trade,
    UniverseMember,
    ValidationDisposition,
)
from .portfolio import simulate_session_portfolio
from .ranking import (
    evaluate_candidate,
    evaluate_opening_range,
    rank_and_select_top_20,
    size_order_intent,
)
from .spec import (
    LOCKED_003B_SPEC_SHA256,
    LOCKED_003C_RESOLUTION_SHA256,
    EffectiveORBSpec,
    SpecError,
    load_effective_spec,
    sha256_of_file,
)

__all__ = [
    "LOCKED_003B_SPEC_SHA256",
    "LOCKED_003C_RESOLUTION_SHA256",
    "BootstrapCI",
    "Candidate",
    "DailyBar",
    "DataIntegrityError",
    "Direction",
    "EffectiveORBSpec",
    "ExitReason",
    "GateEvaluationResult",
    "HoldoutAccessDeniedError",
    "HoldoutAccessProof",
    "MinuteBar",
    "ORBEvaluator",
    "OpeningRange",
    "OpeningRangeVolumeObservation",
    "OrderIntent",
    "OrderStatus",
    "RankedCandidate",
    "SessionResult",
    "SpecError",
    "StudyMetrics",
    "StudyResult",
    "Trade",
    "TwoStageDatasetManifest",
    "UniverseMember",
    "ValidationDisposition",
    "build_trade_record",
    "check_protective_stop_hit",
    "check_same_bar_stop_collision",
    "check_stop_entry_trigger",
    "compute_adv14",
    "compute_atr14_wilder",
    "compute_manifest_sha256",
    "compute_relative_volume",
    "compute_study_metrics",
    "evaluate_candidate",
    "evaluate_opening_range",
    "evaluate_validation_disposition",
    "load_effective_spec",
    "manifest_from_dict",
    "manifest_from_json",
    "manifest_to_dict",
    "manifest_to_json",
    "rank_and_select_top_20",
    "run_session_date_bootstrap",
    "sha256_of_file",
    "simulate_session_portfolio",
    "size_order_intent",
    "validate_dataset_manifest_invariants",
    "verify_holdout_access_guard",
]
